project_path: path/to/this/repo
hydra_root: ${user_settings.project_path}/hydra
hydra_dir: ${user_settings.hydra_root}/${now:%Y-%m-%d}/${now:%H-%M-%S}
result_dir: ${user_settings.hydra_dir}
dataset_path: path/to/your/datasets
model_path: path/to/your/models

reddit:
  client_id: YOUR_CLIENT_ID
  client_secret: YOUR_CLIENT_SECRET
  user_agent: YOUR_USER_AGENT

