hydra_root: ${oc.env:KYGS_HYDRA_PATH, /tmp/kygs_hydra}
hydra_dir: ${user_settings.hydra_root}/${now:%Y-%m-%d}/${now:%H-%M-%S}
result_dir: ${user_settings.hydra_dir}
dataset_path: ${oc.env:KYGS_DATASET_PATH, null}
model_path: ${oc.env:KYGS_MODEL_PATH, null}

reddit:
  client_id: ${oc.env:KYGS_REDDIT_CLIENT_ID, null}
  client_secret: ${oc.env:KYGS_REDDIT_CLIENT_SECRET, null}
  user_agent: python

