_target_: kygs.summarization.direct.OnlyMessageSummarizationPrompt
system_prompt: "You are a helpful assistant whose role is to summarize information from posts. Follow the instructions as closely as possible."
user_prompt_template: |
  ### Instruction ###
  Below are summaries of the text posts collected on a social platform and stored in JSON. Write a summary based on them using up to three sentences. 

  ### Posts ###
  {messages_as_json}
