
defaults:
  - _self_
  - user_settings: user_settings
  - hydra: base

project_path: ${user_settings.project_path}
result_dir: ${user_settings.result_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}

reddit:
  labels:
    - gpt5
    - gpt4o
    - gpt-oss
    - qwen
    - other_llms
    - other
  input_file: hydra/2025-08-10/06-46-20/reddit_posts_20250810_064653.json
  annotated_dataset_path: ${user_settings.datasets}/annotated_posts.json
